using System.IO.Compression;
using System.Text;
using Microsoft.Extensions.Logging;
using RedNb.Nacos.Core.Ai;

namespace RedNb.Nacos.Sample.AI;

/// <summary>
/// Skill section of the sample: builds a minimal skill package in memory and drives the
/// full skill lifecycle over the HTTP channel — ZIP upload, submit for review, publish,
/// bring online, download the published ZIP back, then take it offline and delete it.
/// The skill registry is HTTP-only on Nacos 3.2.4 (the gRPC AI service delegates every
/// skill call to the same HTTP sub-service), so the gRPC handle is unused here.
/// </summary>
public static class SkillSamples
{
    public static async Task<SampleResult> RunAsync(
        IAiService httpAi,
        IAiService grpcAi, // unused: skill registry APIs are HTTP-only on Nacos 3.2.4
        ILogger logger,
        CancellationToken ct)
    {
        var skillName = $"doc-writer-{DateTime.UtcNow:yyyyMMddHHmmss}";
        const string version = "1.0.0";

        try
        {
            // 1. Build a minimal skill package in memory. The server parses the upload
            //    with SkillZipParser: SKILL.md is mandatory, its YAML front matter must
            //    carry a non-blank name and description, and a markdown body must follow
            //    the closing ---. Lines are joined with "\n" so the package uses the LF
            //    line breaks the server's front-matter parser is written against.
            var skillMd = string.Join('\n', new[]
            {
                "---",
                $"name: {skillName}",
                "description: Sample skill generated by RedNb.Nacos.Sample.AI.",
                $"version: {version}",
                "---",
                string.Empty,
                "# Sample Skill",
                string.Empty,
                "Generated by the AI sample for the ZIP upload/download demo.",
                string.Empty
            });

            byte[] zipBytes;
            using (var ms = new MemoryStream())
            {
                using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
                {
                    var entry = zip.CreateEntry("SKILL.md");
                    await using var entryStream = entry.Open();
                    await entryStream.WriteAsync(Encoding.UTF8.GetBytes(skillMd), ct);
                }

                zipBytes = ms.ToArray();
            }

            logger.LogInformation("[Skill] uploading {Bytes} bytes for {Name}", zipBytes.Length, skillName);
            // HTTP: admin upload (v3/admin/ai/skills/upload). The upload lands as a draft
            //       version; the front-matter version above is the source the server resolves
            //       it from first, and targetVersion repeats it so the same 1.0.0 comes out
            //       whichever source wins.
            await httpAi.UploadSkillZipAsync(
                zipBytes, $"{skillName}.zip", targetVersion: version, cancellationToken: ct);

            // 2. Draft -> reviewing -> online. A Nacos publish pipeline runs only when an
            //    AI pipeline plugin is installed (off by default), so with no plugin the
            //    submit publishes the version straight away and the explicit publish below
            //    is idempotent; with a pipeline configured the version waits in reviewing
            //    and the publish call surfaces the server's refusal.
            // HTTP: draft -> reviewing.
            await httpAi.SubmitSkillReviewAsync(skillName, version, cancellationToken: ct);
            logger.LogInformation("[Skill] submitted for review");

            // HTTP: reviewing -> online; updateLatestLabel moves the "latest" label along.
            await httpAi.PublishSkillAsync(
                skillName, version, updateLatestLabel: true, cancellationToken: ct);

            // HTTP: explicit online switch with the public scope; a no-op once publish
            //       has already made the version online.
            await httpAi.OnlineSkillAsync(
                skillName, version, scope: AiConstants.Skill.ScopePublic, cancellationToken: ct);
            logger.LogInformation("[Skill] published + online");

            // 3. Read the package back through the client route. The server re-zips the
            //    stored skill, so the entry is <skillName>/SKILL.md and the markdown is
            //    normalised server-side — only the shape of the artifact is asserted,
            //    never byte equality with the upload.
            // HTTP: client download (v3/client/ai/skills) with md5/resolved-version headers.
            var downloaded = await httpAi.DownloadSkillZipByVersionAsync(
                skillName, version, cancellationToken: ct);
            if (downloaded is null)
            {
                return new SampleResult(SampleOutcome.Failed,
                    "DownloadSkillZipByVersion returned null after publish");
            }

            var entries = ListZipEntries(downloaded.ZipContent);
            logger.LogInformation("[Skill] downloaded {Bytes} bytes md5={Md5} version={Version} entries=[{Entries}]",
                downloaded.ZipContent.Length, downloaded.Md5, downloaded.Version,
                string.Join(", ", entries));

            if (!entries.Any(name => name.EndsWith("SKILL.md", StringComparison.OrdinalIgnoreCase)))
            {
                return new SampleResult(SampleOutcome.Failed,
                    $"Downloaded package has no SKILL.md entry (entries: {string.Join(", ", entries)})");
            }

            // 4. Cleanup: take the version offline, then delete the skill. The server's
            //    DELETE route binds only the skill name, so the version argument is
            //    ignored and every version of the demo skill goes away with it.
            // HTTP: online -> offline.
            await httpAi.OfflineSkillAsync(skillName, version, cancellationToken: ct);
            // HTTP: delete the skill.
            await httpAi.DeleteSkillAsync(skillName, version, cancellationToken: ct);

            return new SampleResult(SampleOutcome.Ok);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "[Skill] failed");
            return new SampleResult(SampleOutcome.Failed, ex.Message);
        }
    }

    /// <summary>
    /// Lists the entry names of a downloaded skill ZIP. An unreadable package yields an
    /// empty list so the caller reports the missing SKILL.md instead of throwing.
    /// </summary>
    private static IReadOnlyList<string> ListZipEntries(byte[] zipBytes)
    {
        try
        {
            using var ms = new MemoryStream(zipBytes);
            using var zip = new ZipArchive(ms, ZipArchiveMode.Read);
            return zip.Entries.Select(entry => entry.FullName).ToList();
        }
        catch (InvalidDataException)
        {
            return [];
        }
    }
}
